# Generated by Django 2.1.3 on 2018-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, to='market.HashTag'),
        ),
        migrations.AddField(
            model_name='shop',
            name='hash_tags',
            field=models.ManyToManyField(blank=True, to='market.HashTag'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='allowed_hash_tags',
            field=models.ManyToManyField(to='market.HashTag'),
        ),
    ]
